import Document,{ Html, Head, Main, NextScript, DocumentContext } from 'next/document'
const urlIcon: string = './icons/';

export default class MyDocument extends Document {
    static async getInitialProps(ctx: DocumentContext) {
        const initialProps = await Document.getInitialProps(ctx)

        return {...initialProps}
    }
    render(): JSX.Element {
        return (
            <Html lang="ru">
                <Head>
                    <meta name="description" content="Generated by create next app" />
                    <link type="image/png" href={urlIcon + "favicon.png"} rel="icon"/>
                </Head>
                <body>
                <Main />
                <NextScript />
                </body>
            </Html>
        )
    }
}
